### ISSUE TITLE
  Polynomial  approach  to  the  solution  of  the  quantum  master  equation

### ISSUE THREAD

**Issue by gharib85** [tmancal74/quantarhei#109]

**Comment by gharib85** [comment]
https://www.researchgate.net/publication/253912997_Interplay_of_non-Markovian_relaxation_and_ultrafast_optical_state_preparation_in_molecular_systems_The_Laguerre_polynomial_method?enrichId=rgreq-5835422e2b4b8c7bd07a680fba1c9305-XXX&enrichSource=Y292ZXJQYWdlOzI1MzkxMjk5NztBUzoyNTkwODIxMDgwMTA0OTZAMTQzODc4MTM5ODA3MQ%3D%3D&el=1_x_3&_esc=publicationCoverPdf

**Comment by tmancal74** [comment]
The requested method is not universal enough for its implementation to make sense for Quantarhei.
